# Exemple de configuration des secrets Streamlit pour SendGrid
# Copiez ce fichier vers secrets.toml et remplissez vos vraies données

# Clé API SendGrid (obtenez-la depuis votre dashboard SendGrid)
SENDGRID_API_KEY = "SG.your_actual_api_key_here"

# Email expéditeur vérifié dans SendGrid
FROM_EMAIL = "noreply@convergence.fr"

# Instructions:
# 1. Copiez ce fichier vers secrets.toml
# 2. Remplacez les valeurs par vos vraies données
# 3. Le fichier secrets.toml sera automatiquement ignoré par Git
